version: 2

updates:
  # Update npm packages
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 10

    # Group packages into shared PR
    groups:
      build:
        patterns:
          - '@babel/*'
          - 'autoprefixer'

      lint:
        patterns:
          - 'prettier'
          - 'stylelint'
          - 'stylelint-*'
          - 'neostandard'

      logging:
        patterns:
          - '*-pino'
          - '*-pino-format'
          - 'pino'
          - 'pino-*'
          - 'aws-embedded-metrics'

      tools:
        patterns:
          - 'husky'
          - 'nodemon'
          - 'npm-run-all'

      vitest:
        patterns:
          - 'vitest'
          - 'vitest-*'
          - '@vitest/*'

      hapi:
        patterns:
          - '@hapi/*'
          - 'hapi-*'
          - '@defra/hapi-*'

      config:
        patterns:
          - 'convict'
          - 'convict-format-with-validator'
          - 'dotenv'

      code:
        patterns:
          - 'https-proxy-agent'
          - 'joi'
          - 'node-fetch'
          - 'undici'

    ignore:
      - dependency-name: 'eslint-*'
      - dependency-name: 'eslint'

    # Schedule run every Monday, local time
    schedule:
      interval: weekly
      time: '10:30'
      timezone: 'Europe/London'

    versioning-strategy: increase

    allow:
      # Include direct package.json updates
      - dependency-type: direct

  # Update GitHub Actions
  - package-ecosystem: github-actions
    directory: /

    # Schedule run every Monday, local time
    schedule:
      interval: weekly
      time: '10:30'
      timezone: 'Europe/London'
