services:
  localstack:
    image: localstack/localstack:3.0.2
    ports:
      - '4566:4566' # LocalStack Gateway
      - '4510-4559:4510-4559' # external services port range
    env_file:
      - 'compose/aws.env'
    environment:
      DEBUG: ${DEBUG:-1}
      LS_LOG: WARN # Localstack DEBUG Level
      SERVICES: s3,sqs,sns,firehose
      LOCALSTACK_HOST: 127.0.0.1
    volumes:
      - '${TMPDIR:-/tmp}/localstack:/var/lib/localstack'
      - ./compose/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh
    healthcheck:
      test: ['CMD', 'curl', 'localhost:4566']
      interval: 5s
      start_period: 5s
      retries: 3
    networks:
      - cdp-tenant

  postgres:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: nrf_backend
    networks:
      - cdp-tenant
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/data
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      retries: 5
      start_period: 1s
      timeout: 10s

  liquibase:
    image: liquibase/liquibase:4.27-alpine
    networks:
      - cdp-tenant
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./changelog:/liquibase/changelog
    command: --url=jdbc:postgresql://postgres:5432/nrf_backend --username=postgres --password=password --changelog-file=changelog/db.changelog.xml update

  ################################################################################

  # frontend:
  #   image: defradigital/frontend:${FRONTEND_VERSION:-latest}
  #   ports:
  #     - '3000:3000'
  #   links:
  #     - 'localstack:localstack'
  #     - 'redis:redis'
  #   depends_on:
  #     localstack:
  #       condition: service_healthy
  #     redis:
  #       condition: service_started
  #   env_file:
  #     - 'compose/aws.env'
  #   environment:
  #     PORT: 3000
  #     NODE_ENV: development
  #     REDIS_HOST: redis
  #     LOCALSTACK_ENDPOINT: http://localstack:4566
  #     USE_SINGLE_INSTANCE_CACHE: true
  #   networks:
  #     - cdp-tenant

  nrf-backend:
    build:
      context: .
      target: development
    ports:
      - '3001:3001'
    links:
      - 'localstack:localstack'
      - 'postgres:postgres'
    depends_on:
      localstack:
        condition: service_healthy
      postgres:
        condition: service_healthy
      liquibase:
        condition: service_started
    env_file:
      - 'compose/aws.env'
    environment:
      PORT: 3001
      NODE_ENV: development
      LOCALSTACK_ENDPOINT: http://localstack:4566
      S3_ENDPOINT: http://localstack:4566
      IMPACT_ASSESSOR_URL: http://host.docker.internal:8085
      DB_HOST: postgres
      CDP_UPLOADER_URL: http://cdp-uploader:7337
    networks:
      - cdp-tenant
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json

  redis:
    image: redis:7.2.3-alpine3.18
    ports:
      - '6380:6379'
    restart: always
    networks:
      - cdp-tenant

  caddy:
    image: caddy:2-alpine
    ports:
      - '4001:4001'
    volumes:
      - ./compose/Caddyfile:/etc/caddy/Caddyfile:ro
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    depends_on:
      - cdp-uploader
    networks:
      - cdp-tenant

  cdp-uploader:
    image: defradigital/cdp-uploader:${CDP_UPLOADER_VERSION:-latest}
    ports:
      - '7337:7337'
    links:
      - 'localstack:localstack'
      - 'redis:redis'
    depends_on:
      localstack:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - 'compose/aws.env'
    environment:
      PORT: 7337
      NODE_ENV: development
      REDIS_HOST: redis
      USE_SINGLE_INSTANCE_CACHE: true
      MOCK_VIRUS_SCAN_ENABLED: true
      MOCK_VIRUS_RESULT_DELAY: 3
      SQS_ENDPOINT: http://localstack:4566
      S3_ENDPOINT: http://localstack:4566
      CONSUMER_BUCKETS: ${CDP_UPLOADER_BUCKET:-boundaries}
    networks:
      - cdp-tenant

################################################################################

volumes:
  postgres-data:

networks:
  cdp-tenant:
    driver: bridge
    name: cdp-tenant
